var Customer="http://bigdata.xytschool.com/api/getCustomerSummary"
 var Vehicles="http://bigdata.xytschool.com/api/getVehiclesSummary"
var comments= "http://bigdata.xytschool.com/api/comments"
// var Customer="http://bigdata.xyt/api/getCustomerSummary"
// var Vehicles="http://bigdata.xyt/api/getVehiclesSummary"
